#!/bin/bash

echo "=========================================="
echo "  Memory Makers APK Build Script"
echo "=========================================="
echo ""
echo "✅ EAS CLI is installed"
echo "✅ App is configured"
echo "✅ Build settings are ready"
echo ""
echo "🔐 Now I need YOU to login..."
echo ""
echo "Please run these 2 commands:"
echo ""
echo "1️⃣  eas login"
echo "    (Enter your Expo email and password)"
echo ""
echo "2️⃣  eas build --platform android --profile preview"
echo "    (This starts the build!)"
echo ""
echo "=========================================="
echo ""
echo "After running these commands:"
echo "- Build takes ~15 minutes"
echo "- You'll get a download link"
echo "- Or check: https://expo.dev"
echo ""
echo "Don't have an Expo account?"
echo "Create free at: https://expo.dev"
echo "=========================================="
